version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/action

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: clear.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ubuntu